import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, test, vi } from "vitest"

type PackageManifest = {
  dependencies?: Record<string, string>
}

type ResolvedNextConfig = {
  experimental?: { useTypeScriptCli?: boolean }
  output?: string
  outputFileTracingRoot?: string
  serverExternalPackages?: readonly string[]
}

const repoRoot = resolve(import.meta.dirname, "../../..")
const nextApps = [
  ["apps/web", "../../../apps/web/next.config.ts"],
  ["packages/inspector", "../next.config.ts"],
  ["examples/chat/web", "../../../examples/chat/web/next.config.mjs"],
  ["examples/research/web", "../../../examples/research/web/next.config.mjs"],
] as const
const nextEnvDeclarations = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
import "./.next/types/routes.d.ts";
import "./.next/types/root-params.d.ts";

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`

function readManifest(appDir: string): PackageManifest {
  return JSON.parse(
    readFileSync(resolve(repoRoot, appDir, "package.json"), "utf8"),
  ) as PackageManifest
}

async function loadConfig(moduleId: string): Promise<ResolvedNextConfig> {
  const configModule = await vi.importActual<{ default: ResolvedNextConfig }>(moduleId)
  return configModule.default
}

describe("Next TypeScript CLI configuration", () => {
  test("pins every Next application to Next 16.3.0", () => {
    for (const [appDir] of nextApps) {
      expect.soft(readManifest(appDir).dependencies?.next, appDir).toBe("16.3.0")
    }
  })

  test("pins the docs MDX integration to Next 16.3.0", () => {
    expect(readManifest("apps/web").dependencies?.["@next/mdx"]).toBe("16.3.0")
  })

  test("enables the TypeScript CLI in every resolved Next configuration", async () => {
    for (const [appDir, moduleId] of nextApps) {
      const config = await loadConfig(moduleId)
      expect.soft(config.experimental?.useTypeScriptCli, appDir).toBe(true)
    }
  })

  test("preserves the Inspector standalone runtime configuration", async () => {
    const inspectorConfig = await loadConfig("../next.config.ts")
    expect(inspectorConfig.output).toBe("standalone")
    expect(inspectorConfig.outputFileTracingRoot).toBe(repoRoot)
    expect(inspectorConfig.serverExternalPackages).toEqual([
      "@dawn-ai/core",
      "@dawn-ai/memory",
      "tsx",
      "typescript",
    ])
  })

  test("tracks the declarations generated by Next 16.3", () => {
    for (const appDir of ["apps/web", "packages/inspector"]) {
      expect
        .soft(readFileSync(resolve(repoRoot, appDir, "next-env.d.ts"), "utf8"), appDir)
        .toBe(nextEnvDeclarations)
    }
  })
})
