import { NextResponse } from "next/server"

function buildLlmsTxt(): string {
  return [
    "# Dawn",
    "",
    "Dawn is a TypeScript-first meta-framework for building graph-based AI agents with the ergonomics of Next.js: file-system routing, co-located tools with inferred types, scenario testing, and a local dev server that speaks the LangGraph Platform protocol natively.",
    "",
    "## Install",
    "```",
    "npx create-dawn-app my-agent",
    "cd my-agent",
    "pnpm install",
    "```",
    "",
    "## Project Shape",
    "- `dawn.config.ts` at repo root (only supported field: `appDir`, defaults to `src/app`).",
    "- `src/app/**/index.ts` — route entry; exports exactly one of `workflow` (async function), `graph` (LangGraph graph), or `chain` (LangChain LCEL Runnable).",
    "- `src/app/**/state.ts` — route state type.",
    "- `src/app/**/tools/*.ts` — co-located tools (default export is an async function; types inferred).",
    "- `src/app/**/run.test.ts` — colocated scenario tests.",
    "- `dawn.generated.d.ts` — auto-generated ambient types. Never edit by hand.",
    "",
    "## Pathname Rules",
    "- Directory path becomes URL pathname.",
    "- `(public)` — route group; excluded from pathname.",
    "- `[tenant]` — dynamic segment; maps to a state field named `tenant`.",
    "- Example: `src/app/(public)/hello/[tenant]/index.ts` → `/hello/[tenant]`.",
    "",
    "## Minimal Route",
    "```ts",
    'import type { RuntimeContext } from "@dawnai.org/sdk"',
    'import type { RouteTools } from "dawn:routes"',
    'import type { HelloState } from "./state.js"',
    "",
    "export async function workflow(",
    "  state: HelloState,",
    '  ctx: RuntimeContext<RouteTools<"/hello/[tenant]">>',
    ") {",
    "  const result = await ctx.tools.greet({ tenant: state.tenant })",
    "  return { ...state, greeting: result.greeting }",
    "}",
    "```",
    "",
    "## Minimal Tool",
    "```ts",
    "// src/app/(public)/hello/[tenant]/tools/greet.ts",
    "export default async (input: { readonly tenant: string }) => {",
    // biome-ignore lint/suspicious/noTemplateCurlyInString: deliberate — this string is a code sample for agent consumption
    "  return { greeting: `Hello, ${input.tenant}!` }",
    "}",
    "```",
    "",
    "## Commands",
    "- `dawn check` — validate app structure/config",
    "- `dawn routes` — list discovered routes",
    "- `dawn typegen` — regenerate `dawn.generated.d.ts`",
    "- `dawn run '/hello/acme'` — execute a route with JSON stdin/stdout",
    "- `dawn test` — run scenarios",
    "- `dawn dev` — local runtime (LangGraph Platform protocol: `/runs/wait`, `/runs/stream`, `assistant_id`)",
    "",
    "## Packages",
    "- `@dawnai.org/sdk` — backend-neutral contract (types, `RuntimeContext`, test helpers)",
    "- `@dawnai.org/langgraph` — LangGraph graphs/workflows adapter",
    "- `@dawnai.org/langchain` — LangChain LCEL adapter",
    "- `@dawnai.org/cli` — the `dawn` CLI",
    "",
    "## Deployment",
    "Dawn owns local development only. Production runs on LangGraph Platform. Routes deploy as LangSmith Assistants keyed by `assistant_id`. The dev server speaks the Platform protocol natively, so what runs locally runs in production without translation.",
    "",
    "## Task-Specific Prompts",
    "Copy-ready prompts for common tasks:",
    "- Scaffold: https://dawnai.org/prompts/scaffold",
    "- Add a tool: https://dawnai.org/prompts/add-a-tool",
    "- Write a route: https://dawnai.org/prompts/write-a-route",
    "- Write a test: https://dawnai.org/prompts/write-a-test",
    "- Deploy: https://dawnai.org/prompts/deploy",
    "",
    "## Agent Config Templates",
    "Drop-in agent configuration for a Dawn project:",
    "- https://dawnai.org/AGENTS.md",
    "- https://dawnai.org/assistant.md",
    "",
    "## Full Reference",
    "https://dawnai.org/llms-full.txt",
    "",
    "## Source",
    "https://github.com/cacheplane/dawnai",
  ].join("\n")
}

export async function GET() {
  return new NextResponse(buildLlmsTxt(), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  })
}
