import { NextResponse } from "next/server"
import { getAllPosts } from "../components/blog/post-index"

function buildLlmsTxt(): string {
  const blogSection = [
    "",
    "## Blog",
    "",
    ...getAllPosts().map(
      (p) => `- [${p.title}](https://dawnai.org/blog/${p.slug}): ${p.description}`,
    ),
  ].join("\n")

  return (
    [
      "# Dawn",
      "",
      "Dawn is a TypeScript-first meta-framework for building graph-based AI agents with the ergonomics of Next.js: file-system routing, co-located tools with inferred types, scenario testing, route-level agent features, durable threads, and a local Agent Protocol dev server.",
      "",
      "## Install",
      "```",
      "pnpm create dawn-ai-app my-agent",
      "cd my-agent",
      "pnpm install",
      "```",
      "",
      "## Project Shape",
      "- `dawn.config.ts` at repo root. Supported keys include `appDir`, `backends`, `permissions`, `checkpointer`, `threadsStore`, `env`, `toolOutput`, `summarization`, `sandbox`, and `memory`.",
      "- `src/app/**/index.ts` — route entry; exports exactly one of default `agent(...)`, named `workflow` (async function), named `graph` (LangGraph graph), or named `chain` (LangChain LCEL Runnable).",
      "- `src/app/**/state.ts` — optional Zod route state schema.",
      "- `src/app/**/tools/*.ts` — co-located tools (default export is an async function; types inferred).",
      "- `workspace/AGENTS.md` — optional workspace guidance injected into agent prompts.",
      "- `src/app/**/plan.md` — optional route-local planning seed; contributes `writeTodos`, `todos`, and `plan_update`.",
      "- `src/app/**/skills/<name>/SKILL.md` — optional route-local skills loaded through `readSkill`.",
      "- `src/app/**/subagents/<name>/index.ts` — optional child agent routes exposed through `task`.",
      "- `agent({ reasoning })` — optional OpenAI-backed reasoning-effort configuration.",
      "- `src/app/**/run.test.ts` — colocated scenario tests.",
      "- `.dawn/dawn.generated.d.ts` — auto-generated ambient types. Never edit by hand.",
      "",
      "## Pathname Rules",
      "- Directory path becomes URL pathname.",
      "- `(public)` — route group; excluded from pathname.",
      "- `[tenant]` — dynamic segment preserved in the route id; provide the value in JSON input.",
      "- Default scaffold example: `src/app/research/index.ts` → `/research`; agent route key `/research#agent`.",
      "- Optional basic scaffold example: `src/app/(public)/hello/[tenant]/index.ts` → `/hello/[tenant]`.",
      "",
      "## Minimal Agent Route",
      "```ts",
      'import { agent } from "@dawn-ai/sdk"',
      "",
      "export default agent({",
      '  model: "gpt-5-mini",',
      '  systemPrompt: "You are a research coordinator. Search the local corpus, dispatch specialists when useful, and cite every claim.",',
      "})",
      "```",
      "",
      "## Minimal Tool",
      "```ts",
      "// src/app/research/tools/searchCorpus.ts",
      "export default async (input: { readonly query: string }) => {",
      '  return [{ path: "corpus/agent-architectures.md", score: 2, snippet: "ReAct and plan-and-execute are common agent architectures." }]',
      "}",
      "```",
      "",
      "## Commands",
      "- `dawn add [name]` — add Dawn-authored templates or components",
      "- `dawn build` — write `.dawn/build/langgraph.json` and per-route entry files",
      "- `dawn check` — validate app structure/config",
      "- `dawn dev` — local Agent Protocol runtime server",
      "- `dawn docs [topic]` — print local documentation snippets",
      "- `dawn eval [path]` — run eval definitions",
      "- `dawn memory [subcommand] [args...]` — inspect and manage long-term memory",
      "- `dawn routes` — list discovered routes",
      "- `dawn run <routePath>` — execute a route with JSON stdin/stdout",
      "- `dawn test [path]` — run scenarios",
      "- `dawn typegen` — regenerate `.dawn/dawn.generated.d.ts`",
      "- `dawn verify` — full integrity check across app, routes, typegen, deps",
      '- `echo \'{"messages":[{"role":"user","content":"What are common agent architectures?"}]}\' | dawn run /research` — execute the default scaffold route',
      "",
      "## Agent Protocol",
      "- `GET /healthz`",
      "- `POST /threads`",
      "- `GET /threads/:thread_id`",
      "- `DELETE /threads/:thread_id`",
      "- `POST /threads/:thread_id/runs/wait`",
      "- `POST /threads/:thread_id/runs/stream`",
      "- `GET /threads/:thread_id/state`",
      "- `POST /threads/:thread_id/resume`",
      '- Run body: `{ "route": "/research#agent", "input": { "messages": [{ "role": "user", "content": "What are common agent architectures?" }] } }`',
      '- Resume body: `{ "interrupt_id": "<id>", "decision": "once" | "always" | "deny", "route": "/research#agent" }`; `route` is optional unless the server cannot recover the route from its in-memory thread map or durable thread metadata.',
      "",
      "## Runtime Capabilities",
      "- `toolOutput` offloads large tool results into `workspace/tool-outputs/` and keeps an in-context preview.",
      "- `summarization` is opt-in and compresses older thread history when configured.",
      "- `memory` enables typed long-term recall/write governance through route-local memory definitions.",
      "- `sandbox` configures isolated execution for workspace commands where supported.",
      "",
      "## Packages",
      "- `@dawn-ai/sdk` — authoring contract (types, `RuntimeContext`, test helpers)",
      "- `@dawn-ai/langgraph` — LangGraph graphs/workflows adapter",
      "- `@dawn-ai/langchain` — LangChain LCEL adapter and provider-aware agent materialization",
      "- `@dawn-ai/cli` — the `dawn` CLI",
      "",
      "## Deployment",
      "Dawn owns local development and the build step. `dawn build` writes `.dawn/build/langgraph.json` plus per-route entry files. Production runs on LangSmith or another runtime that consumes those generated LangGraph artifacts.",
      "",
      "## Task-Specific Prompts",
      "Copy-ready prompts for common tasks:",
      "- Scaffold: https://dawnai.org/prompts/scaffold",
      "- Add a tool: https://dawnai.org/prompts/add-a-tool",
      "- Write a route: https://dawnai.org/prompts/write-a-route",
      "- Write a test: https://dawnai.org/prompts/write-a-test",
      "- Deploy: https://dawnai.org/prompts/deploy",
      "",
      "## Agent Config Templates",
      "Drop-in agent configuration for a Dawn project:",
      "- https://dawnai.org/AGENTS.md",
      "",
      "## Brand Assets",
      "Official Dawn AI logos, icons, favicons, and social assets:",
      "- Asset manifest: https://dawnai.org/brand/assets.json",
      "- Full brand kit ZIP: https://dawnai.org/brand/dawn-ai-brand-assets.zip",
      "",
      "## Full Reference",
      "https://dawnai.org/llms-full.txt",
      "",
      "## Source",
      "https://github.com/cacheplane/dawnai",
    ].join("\n") + blogSection
  )
}

export async function GET() {
  return new NextResponse(buildLlmsTxt(), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  })
}
