import { mkdir, mkdtemp, realpath, rm, symlink, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { discoverRoutes } from "@dawn-ai/core"
import { afterEach, describe, expect, test } from "vitest"
import { run } from "../src/index.js"
import {
  collectRouteStaticDiscovery,
  emitModulesFile,
  type RouteStaticDiscovery,
} from "../src/lib/build/targets/modules-emitter.js"

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")

const tempDirs: string[] = []

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map((dir) =>
      rm(dir, {
        force: true,
        maxRetries: 5,
        recursive: true,
        retryDelay: 100,
      }),
    ),
  )
})

async function createFixtureApp(files: Readonly<Record<string, string>>): Promise<string> {
  // realpath: on macOS the tmpdir is behind a /var → /private/var symlink and
  // the loader resolves module URLs to real paths — keep everything resolved.
  const appRoot = await realpath(await mkdtemp(join(tmpdir(), "dawn-static-check-")))
  tempDirs.push(appRoot)

  const appFiles = {
    "dawn.config.ts": "export default {};\n",
    "package.json": '{"type":"module"}\n',
    ...files,
  }

  await Promise.all(
    Object.entries(appFiles).map(async ([relativePath, source]) => {
      const filePath = join(appRoot, relativePath)
      await mkdir(dirname(filePath), { recursive: true })
      await writeFile(filePath, source)
    }),
  )

  return appRoot
}

async function invoke(argv: readonly string[]) {
  const stdout: string[] = []
  const stderr: string[] = []

  const exitCode = await run([...argv], {
    stderr: (message: string) => {
      stderr.push(message)
    },
    stdout: (message: string) => {
      stdout.push(message)
    },
  })

  return {
    exitCode,
    stderr: stderr.join(""),
    stdout: stdout.join(""),
  }
}

async function writeManifest(appRoot: string, text: string): Promise<string> {
  const buildDir = join(appRoot, ".dawn", "build")
  await mkdir(buildDir, { recursive: true })
  const modulesPath = join(buildDir, "modules.mjs")
  await writeFile(modulesPath, text, "utf8")
  return modulesPath
}

/** Generate a REAL manifest for the app's current routes via the emitter. */
async function emitRealManifest(appRoot: string): Promise<string> {
  // The emitted manifest imports "@dawn-ai/cli/runtime" — link the real
  // package so it resolves from the tmpdir fixture (modules-emitter pattern).
  await mkdir(join(appRoot, "node_modules", "@dawn-ai"), { recursive: true })
  await symlink(
    join(repoRoot, "packages", "cli"),
    join(appRoot, "node_modules", "@dawn-ai", "cli"),
    "dir",
  )

  const manifest = await discoverRoutes({ appRoot })
  const discoveries: RouteStaticDiscovery[] = []
  for (const route of manifest.routes) {
    discoveries.push(await collectRouteStaticDiscovery({ appRoot, route }))
  }
  const buildDir = join(appRoot, ".dawn", "build")
  return await writeManifest(appRoot, emitModulesFile({ appRoot, buildDir, discoveries }))
}

describe("dawn check — static module manifest staleness", () => {
  test("no manifest present: check passes untouched", async () => {
    const appRoot = await createFixtureApp({
      "src/app/hello/index.ts": "export const workflow = async () => ({ ok: true });\n",
    })

    const result = await invoke(["check", "--cwd", appRoot])

    expect(result.exitCode).toBe(0)
    expect(result.stderr).toBe("")
    expect(result.stdout).toContain("Dawn app is valid")
    expect(result.stdout).not.toContain("manifest")
  })

  test("fresh manifest (generated by the real emitter): check passes", async () => {
    const appRoot = await createFixtureApp({
      "src/app/hello/index.ts": "export const workflow = async () => ({ ok: true });\n",
      "src/tools/greet.ts": "export default async (_input: unknown) => ({ greeting: 'hi' });\n",
    })
    await emitRealManifest(appRoot)

    const result = await invoke(["check", "--cwd", appRoot])

    expect(result.exitCode).toBe(0)
    expect(result.stderr).toBe("")
    expect(result.stdout).toContain("Dawn app is valid")
  })

  test("stale manifest (route renamed after generation): error names BOTH ids and advises dawn build", async () => {
    const appRoot = await createFixtureApp({
      "src/app/new/index.ts": "export const workflow = async () => ({ ok: true });\n",
    })
    // A loadable manifest generated before the route was renamed /old → /new.
    // (A rename that deletes the old sources instead makes the manifest's
    // static imports fail to resolve — that path is covered by the corrupt-
    // manifest test below.)
    await writeManifest(appRoot, 'export default { routes: [{ assistantId: "/old#workflow" }] }\n')

    const result = await invoke(["check", "--cwd", appRoot])

    expect(result.exitCode).toBe(1)
    expect(result.stderr).toContain("Stale static module manifest")
    // Both sides of the rename are named: the id the app now has (missing from
    // the manifest) and the id only the manifest still has (extra).
    expect(result.stderr).toContain("/new#workflow")
    expect(result.stderr).toContain("/old#workflow")
    expect(result.stderr).toContain("dawn build")
  })

  test("corrupt manifest (fails to load): clean check error, not a crash", async () => {
    const appRoot = await createFixtureApp({
      "src/app/hello/index.ts": "export const workflow = async () => ({ ok: true });\n",
    })
    await writeManifest(appRoot, "this is {{{ not javascript\n")

    const result = await invoke(["check", "--cwd", appRoot])

    expect(result.exitCode).toBe(1)
    expect(result.stderr).toContain("Static module manifest")
    expect(result.stderr).toContain("failed to load")
    expect(result.stderr).toContain("dawn build")
  })

  test("manifest with stale imports (route dir renamed, files gone): clean check error", async () => {
    const appRoot = await createFixtureApp({
      "src/app/old/index.ts": "export const workflow = async () => ({ ok: true });\n",
    })
    await emitRealManifest(appRoot)
    // Rename the route post-generation: the manifest's static import of
    // ../../src/app/old/index.js can no longer resolve.
    const { rename } = await import("node:fs/promises")
    await rename(join(appRoot, "src/app/old"), join(appRoot, "src/app/renamed"))

    const result = await invoke(["check", "--cwd", appRoot])

    expect(result.exitCode).toBe(1)
    expect(result.stderr).toContain("Static module manifest")
    expect(result.stderr).toContain("failed to load")
    expect(result.stderr).toContain("dawn build")
  })
})
