import { spawn } from "node:child_process"
import { chmod, cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"

import { afterEach, describe, expect, test } from "vitest"

const REPOSITORY_ROOT = resolve(__dirname, "../..")
const SCRIPT_SOURCE = resolve(REPOSITORY_ROOT, "test/k8s-smoke/build-image.sh")
const temporaryDirectories: string[] = []
const REGISTRY_URL = "http://127.0.0.1:4873"
const POLICY = JSON.stringify({
  images: { packagedAppBase: `node:24-slim@sha256:${"a".repeat(64)}` },
})
const FAKE_DAWN = `#!/bin/sh
mkdir -p .dawn/build
printf 'server output\n' > .dawn/build/server.mjs
cat > Dockerfile <<'EOF'
# Generated by dawn build (node target)
FROM node:24-slim
RUN npm ci
EOF
`

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  )
})

async function writeExecutable(path: string, content: string): Promise<void> {
  await writeFile(path, content)
  await chmod(path, 0o755)
}

async function createFixture(): Promise<{
  root: string
  script: string
  log: string
  dockerfiles: string
  dawn: string
  path: string
}> {
  const root = await mkdtemp(join(tmpdir(), "dawn-build-image-"))
  temporaryDirectories.push(root)
  const smokeDir = join(root, "test", "k8s-smoke")
  const appDir = join(smokeDir, "app")
  const dawn = join(appDir, "node_modules", ".bin", "dawn")
  const binDir = join(root, "bin")
  const log = join(root, "commands.log")
  const dockerfiles = join(root, "dockerfiles")
  await Promise.all([
    mkdir(join(root, ".github"), { recursive: true }),
    mkdir(join(appDir, "node_modules", ".bin"), { recursive: true }),
    mkdir(binDir, { recursive: true }),
  ])
  await Promise.all([
    writeFile(join(root, ".github", "kubernetes-compatibility.json"), POLICY),
    writeFile(join(appDir, "package.json"), "{}\n"),
    writeFile(join(log), ""),
    writeFile(join(dockerfiles), ""),
    cp(SCRIPT_SOURCE, join(smokeDir, "build-image.sh")),
  ])
  await writeExecutable(
    join(binDir, "pnpm"),
    `#!/bin/sh
printf 'pnpm %s\n' "$*" >> "$FAKE_LOG"
exit 0
`,
  )
  await writeExecutable(dawn, FAKE_DAWN)
  await writeExecutable(
    join(binDir, "docker"),
    `#!/bin/sh
printf 'docker %s\n' "$*" >> "$FAKE_LOG"
if [ "$1" = version ]; then
  printf 'amd64\n'
  exit 0
fi
if [ "$1" = build ]; then
  dockerfile=''
  output=''
  while [ "$#" -gt 0 ]; do
    case "$1" in
      -f) dockerfile=$2; shift 2 ;;
      -t) output=$2; shift 2 ;;
      *) shift ;;
    esac
  done
  printf '%s\n---%s---\n' "$output" "$(cat "$dockerfile")" >> "$FAKE_DOCKERFILES"
fi
`,
  )
  await writeExecutable(
    join(binDir, "curl"),
    `#!/bin/sh
printf 'curl %s\n' "$*" >> "$FAKE_LOG"
while [ "$#" -gt 0 ]; do
  if [ "$1" = -o ]; then
    : > "$2"
    exit 0
  fi
  shift
done
`,
  )
  await writeExecutable(
    join(binDir, "tar"),
    `#!/bin/sh
printf 'tar %s\n' "$*" >> "$FAKE_LOG"
while [ "$#" -gt 0 ]; do
  if [ "$1" = -C ]; then
    context=$2
    mkdir -p "$context/docker"
    printf '#!/bin/sh\n' > "$context/docker/docker"
    chmod 755 "$context/docker/docker"
    exit 0
  fi
  shift
done
`,
  )
  return {
    root,
    script: join(smokeDir, "build-image.sh"),
    log,
    dockerfiles,
    dawn,
    path: `${binDir}:${process.env.PATH ?? ""}`,
  }
}

async function runFixture(fixture: Awaited<ReturnType<typeof createFixture>>, args: string[]) {
  await mkdir(dirname(fixture.dawn), { recursive: true })
  await writeExecutable(fixture.dawn, FAKE_DAWN)
  return new Promise<{ code: number | null; stdout: string; stderr: string }>(
    (resolveRun, reject) => {
      const child = spawn("sh", [fixture.script, ...args], {
        cwd: fixture.root,
        env: {
          ...process.env,
          PATH: fixture.path,
          FAKE_LOG: fixture.log,
          FAKE_DOCKERFILES: fixture.dockerfiles,
        },
      })
      let stdout = ""
      let stderr = ""
      child.stdout.on("data", (chunk: Buffer) => {
        stdout += chunk.toString()
      })
      child.stderr.on("data", (chunk: Buffer) => {
        stderr += chunk.toString()
      })
      child.on("error", reject)
      child.on("close", (code) => resolveRun({ code, stdout, stderr }))
    },
  )
}

describe("k8s smoke image tags", () => {
  test("supports default, run-unique, and Docker variant tags", async () => {
    const fixture = await createFixture()

    expect((await runFixture(fixture, ["k8s", REGISTRY_URL])).code).toBe(0)
    expect(
      (await runFixture(fixture, ["k8s", REGISTRY_URL, "dawn-smoke-app:k8s-run123"])).code,
    ).toBe(0)
    expect(
      (await runFixture(fixture, ["docker", REGISTRY_URL, "dawn-smoke-app:docker-run123"])).code,
    ).toBe(0)

    const dockerfileLog = await readFile(fixture.dockerfiles, "utf8")
    expect(dockerfileLog).toContain("dawn-smoke-app:k8s\n")
    expect(dockerfileLog).toContain("dawn-smoke-app:k8s-run123\n")
    expect(dockerfileLog).toContain("dawn-smoke-app:docker-run123\n")
    expect(dockerfileLog).toContain("FROM dawn-smoke-app:docker-run123")
    expect(dockerfileLog.match(/dawn-smoke-app:docker-run123\n/g)).toHaveLength(3)
  })

  test.each(["", "dawn-smoke-app:bad tag"])(
    "rejects an explicitly empty or whitespace-containing tag (%j) before side effects",
    async (tag) => {
      const fixture = await createFixture()
      const result = await runFixture(fixture, ["k8s", REGISTRY_URL, tag])

      expect(result.code).toBe(2)
      expect(await readFile(fixture.log, "utf8")).toBe("")
    },
  )
})
