export type PromptSlug = "scaffold" | "add-a-tool" | "write-a-route" | "write-a-test" | "deploy"

export interface PromptEntry {
  readonly slug: PromptSlug
  readonly title: string
  readonly description: string
  readonly body: string
}

const SCAFFOLD = `Help me scaffold a new Dawn app. Dawn is a TypeScript-first meta-framework for building graph-based AI agents with the ergonomics of Next.js (file-system routing, co-located tools, type inference).

1. Run the scaffold:
   \`\`\`
   npx create-dawn-app my-agent
   cd my-agent
   pnpm install
   \`\`\`

2. Walk me through the generated \`src/app/\` structure. Explain:
   - How routes are directories containing an \`index.ts\` that exports exactly one of: \`workflow\` (async function), \`graph\` (LangGraph graph), or \`chain\` (LangChain LCEL Runnable).
   - \`state.ts\` — the route state type.
   - \`tools/\` — co-located tools, auto-discovered and typed.
   - Route groups like \`(public)\` — excluded from pathname.
   - Dynamic segments like \`[tenant]\` — extracted at runtime.
   - \`dawn.generated.d.ts\` — auto-generated ambient types from the TypeScript compiler API.

3. Run the scaffolded route end-to-end:
   \`\`\`
   dawn run '/hello/acme'
   \`\`\`

4. Start the dev server:
   \`\`\`
   dawn dev
   \`\`\`

5. Summarize what I can build next: add a tool, add a new route, write a scenario test.

Key packages: \`@dawnai.org/sdk\` (backend-neutral contract), \`@dawnai.org/langgraph\` (graphs/workflows), \`@dawnai.org/langchain\` (LCEL), \`@dawnai.org/cli\` (CLI).

Reference: https://dawnai.org/llms.txt
`

const ADD_A_TOOL = `Help me add a new tool to an existing Dawn app. Tools are co-located with the route that uses them and their types are auto-generated by Dawn's TypeScript compiler API integration — no Zod schemas, no manual type wiring.

1. Inside an existing route directory (e.g. \`src/app/(public)/hello/[tenant]/\`), create a \`tools/\` subdirectory if one doesn't exist. Add a new TypeScript file with a default export that is an async function:

   \`\`\`ts
   // src/app/(public)/hello/[tenant]/tools/<tool-name>.ts
   export default async (input: { readonly /* fields */ }) => {
     // do work
     return { /* output */ }
   }
   \`\`\`

2. The input parameter type and the return type are both inferred. Dawn extracts them at build time and writes them into \`dawn.generated.d.ts\`. The tool becomes available on the \`ctx.tools\` object in the route's workflow/graph/chain with full autocomplete.

3. Run \`dawn typegen\` to regenerate types after adding the tool (or leave \`dawn dev\` running — it does this on every file save).

4. Update the route's \`index.ts\` to call the new tool via \`ctx.tools.<tool-name>({ ... })\` and show me the diff.

5. Re-run the route with \`dawn run\` and confirm the new tool is invoked end-to-end.

Constraints:
- The default export must be a function (arrow or async function declaration).
- Input and output types must be serializable as JSON.
- \`readonly\` is recommended on input fields; Dawn preserves it through type generation.

Reference: https://dawnai.org/llms.txt
`

const WRITE_A_ROUTE = `Help me add a new route to an existing Dawn app. Routes are directories under \`src/app/\` where each directory maps to a URL-style pathname (minus route groups).

1. Create the route directory. For a public route under a \`[tenant]\` dynamic segment:
   \`\`\`
   src/app/(public)/<new-route>/[tenant]/
   \`\`\`

2. Create \`state.ts\` — the route's state type:
   \`\`\`ts
   export interface <RouteName>State {
     readonly tenant: string
     // additional fields the route reads/writes
   }
   \`\`\`

3. Create \`index.ts\` — the route entry. Export exactly ONE of:

   **Workflow** (async function, most common):
   \`\`\`ts
   import type { RuntimeContext } from "@dawnai.org/sdk"
   import type { RouteTools } from "dawn:routes"
   import type { <RouteName>State } from "./state.js"

   export async function workflow(
     state: <RouteName>State,
     ctx: RuntimeContext<RouteTools<"/<route-path>">>
   ) {
     // use ctx.tools.<toolName>() — fully typed
     return { ...state, /* updates */ }
   }
   \`\`\`

   **Graph** (LangGraph graph/workflow):
   \`\`\`ts
   export const graph = /* langgraph graph instance */
   \`\`\`

   **Chain** (LangChain LCEL Runnable):
   \`\`\`ts
   export const chain = /* LCEL runnable */
   \`\`\`

4. Optionally create a \`tools/\` directory with co-located tools (see the "Add a tool" prompt).

5. Run \`dawn routes\` to confirm Dawn discovered the new route and what pathname it computed. Then \`dawn run '<pathname>'\` with the required state via stdin.

Constraints:
- Exactly one of \`workflow\`, \`graph\`, or \`chain\` may be exported from \`index.ts\`.
- Route groups in parentheses \`(public)\` are NOT part of the pathname.
- Dynamic segments \`[tenant]\` map to state fields of the same name.
- The \`RouteTools<"/path">\` type is auto-generated from tools in the route's \`tools/\` directory.

Reference: https://dawnai.org/llms.txt
`

const WRITE_A_TEST = `Help me write a scenario test for a Dawn route. Dawn tests run with \`dawn test\`, are co-located with the route, and take the form of \`run.test.ts\` files that declare input state and expected output.

1. In the route directory, create \`run.test.ts\`:

   \`\`\`ts
   import { describe, test } from "@dawnai.org/sdk/testing"

   describe("/<route-path>", () => {
     test("greets a single tenant", {
       input: { tenant: "acme" },
       expected: { tenant: "acme", greeting: "Hello, acme!" },
     })

     test("handles a different tenant", {
       input: { tenant: "globex" },
       expected: { tenant: "globex", greeting: "Hello, globex!" },
     })
   })
   \`\`\`

2. \`input\` is the route's state — it must match the route's \`state.ts\` type.

3. \`expected\` is what the route should return after the workflow/graph/chain runs.

4. Run the scenarios:
   \`\`\`
   dawn test
   \`\`\`

5. Dawn runs each test against the in-process route runtime by default. Use \`--url http://127.0.0.1:3001\` to run against a live \`dawn dev\` server instead, confirming deployment parity.

6. For tools that make external calls (APIs, databases), stub them via \`ctx.tools\` overrides:
   \`\`\`ts
   test("with mocked tool", {
     input: { tenant: "acme" },
     expected: { tenant: "acme", greeting: "Hi from mock!" },
     tools: {
       greet: async () => ({ greeting: "Hi from mock!" }),
     },
   })
   \`\`\`

Constraints:
- \`run.test.ts\` must live in the route's directory, not a sibling.
- The test describes the route path as its top-level \`describe\` block.
- \`expected\` is compared deep-equal to the route's output by default.

Reference: https://dawnai.org/llms.txt
`

const DEPLOY = `Help me deploy a Dawn app. Dawn itself is not a deployment runtime — it owns local development. Production runs on the LangGraph Platform, which Dawn's dev server already speaks natively (\`/runs/wait\`, \`/runs/stream\`, \`assistant_id\` routing). What runs locally deploys without translation.

1. Verify the app is production-ready:
   \`\`\`
   dawn check
   dawn routes
   dawn typegen
   dawn test
   \`\`\`
   All must pass. \`dawn check\` validates the app contract; \`dawn routes\` confirms discovery; \`dawn typegen\` ensures ambient types are current; \`dawn test\` runs scenario tests against the in-process runtime.

2. Confirm protocol parity with LangGraph Platform by pointing \`dawn test\` at a live dev server:
   \`\`\`
   dawn dev --port 3001 &
   dawn test --url http://127.0.0.1:3001
   \`\`\`
   If both pass, the same inputs will pass on LangGraph Platform.

3. Each Dawn route becomes a LangSmith Assistant. Configure deployment:
   - Create a \`langgraph.json\` at the app root describing which routes export a \`graph\` or \`workflow\` and should be deployed.
   - Push to a Git remote connected to the LangGraph Platform.
   - The Platform builds the image and provisions assistants keyed by \`assistant_id\`.

4. Show me a minimal \`langgraph.json\` example that maps Dawn's discovered routes to LangGraph assistants.

5. For infrastructure outside LangGraph Platform (self-hosted, other clouds), explain how to wrap Dawn's runtime in a Docker container that exposes the same \`/runs/wait\` and \`/runs/stream\` endpoints — Dawn's dev server implementation is the reference.

Reference: https://dawnai.org/llms.txt
`

export const PROMPTS: readonly PromptEntry[] = [
  {
    slug: "scaffold",
    title: "Scaffold a new Dawn app",
    description: "Create a new Dawn project and walk through the structure.",
    body: SCAFFOLD,
  },
  {
    slug: "add-a-tool",
    title: "Add a tool",
    description: "Add a type-inferred tool to an existing route.",
    body: ADD_A_TOOL,
  },
  {
    slug: "write-a-route",
    title: "Write a route",
    description: "Create a new route with workflow/graph/chain.",
    body: WRITE_A_ROUTE,
  },
  {
    slug: "write-a-test",
    title: "Write a scenario test",
    description: "Write a colocated run.test.ts for a route.",
    body: WRITE_A_TEST,
  },
  {
    slug: "deploy",
    title: "Deploy",
    description: "Ship a Dawn app to LangGraph Platform.",
    body: DEPLOY,
  },
]

export function getPrompt(slug: PromptSlug): PromptEntry {
  const entry = PROMPTS.find((p) => p.slug === slug)
  if (!entry) {
    throw new Error(`Unknown prompt slug: ${slug}`)
  }
  return entry
}
