export type PromptSlug =
	| "scaffold"
	| "add-a-tool"
	| "write-a-route"
	| "write-a-test"
	| "deploy";

export interface PromptEntry {
	readonly slug: PromptSlug;
	readonly title: string;
	readonly description: string;
	readonly body: string;
}

const SCAFFOLD = `Help me scaffold a new Dawn app. Dawn is a TypeScript-first meta-framework for building graph-based AI agents with the ergonomics of Next.js (file-system routing, co-located tools, type inference).

1. Run the scaffold:
   \`\`\`
   pnpm create dawn-ai-app my-agent
   cd my-agent
   pnpm install
   \`\`\`

2. Walk me through the generated \`src/app/\` structure. Explain:
   - How routes are directories containing an \`index.ts\` that exports exactly one of: default \`agent(...)\`, named \`workflow\` (async function), named \`graph\` (LangGraph graph), or named \`chain\` (LangChain LCEL Runnable).
   - \`state.ts\` — the optional Zod route state schema.
   - \`tools/\` — co-located tools, auto-discovered and typed.
   - Route groups like \`(public)\` — excluded from pathname.
   - Dynamic segments like \`[tenant]\` — preserved in the route id; provide values in JSON input when invoking the route.
   - \`.dawn/dawn.generated.d.ts\` — auto-generated ambient types from the TypeScript compiler API.

3. Run the scaffolded route end-to-end:
   \`\`\`
   echo '{"tenant":"acme"}' | dawn run '/hello/[tenant]'
   \`\`\`

4. Start the dev server:
   \`\`\`
   dawn dev
   \`\`\`

5. Summarize what I can build next: add a tool, add a new route, write a scenario test.

Key packages: \`@dawn-ai/sdk\` (authoring contract), \`@dawn-ai/langgraph\` (graphs/workflows), \`@dawn-ai/langchain\` (LCEL and provider-aware agent materialization), \`@dawn-ai/cli\` (CLI).

Reference: https://dawnai.org/llms.txt
`;

const ADD_A_TOOL = `Help me add a new tool to an existing Dawn app. Tools are co-located with the route that uses them and their types are auto-generated by Dawn's TypeScript compiler API integration — no Zod schemas, no manual type wiring.

1. Inside an existing route directory (e.g. \`src/app/(public)/hello/[tenant]/\`), create a \`tools/\` subdirectory if one doesn't exist. Add a new TypeScript file with a default export that is an async function:

   \`\`\`ts
   // src/app/(public)/hello/[tenant]/tools/<tool-name>.ts
   export default async (input: { readonly /* fields */ }) => {
     // do work
     return { /* output */ }
   }
   \`\`\`

2. The input parameter type and the return type are both inferred. Dawn extracts them at build time and writes them into \`.dawn/dawn.generated.d.ts\`. The tool becomes available on the \`ctx.tools\` object in the route's workflow/graph with full autocomplete, and \`dawn build\` wires it into generated agent entries.

3. Run \`dawn typegen\` to regenerate types after adding the tool (or leave \`dawn dev\` running — it does this on every file save).

4. For a \`workflow\` or \`graph\` route, update \`index.ts\` to call the new tool via \`ctx.tools.<tool-name>({ ... })\` and show me the diff. For an \`agent\` route, leave \`index.ts\` as the default \`agent(...)\` descriptor and rely on \`dawn build\` to wire the tool into the generated graph.

5. Re-run the route with \`dawn run\` and confirm the new tool is invoked end-to-end.

Constraints:
- The default export must be a function (arrow or async function declaration).
- Input and output types must be serializable as JSON.
- \`readonly\` is recommended on input fields; Dawn preserves it through type generation.

Reference: https://dawnai.org/llms.txt
`;

const WRITE_A_ROUTE = `Help me add a new route to an existing Dawn app. Routes are directories under \`src/app/\` where each directory maps to a URL-style pathname (minus route groups).

1. Create the route directory. For a public route under a \`[tenant]\` dynamic segment:
   \`\`\`
   src/app/(public)/<new-route>/[tenant]/
   \`\`\`

2. Optionally create \`state.ts\` — the route's Zod state schema:
   \`\`\`ts
   import { z } from "zod"

   export default z.object({
     question: z.string().default(""),
   })
   \`\`\`

3. Create \`index.ts\` — the route entry. Export exactly ONE of:

   **Workflow** (async function, most common):
   \`\`\`ts
   import type { RuntimeContext } from "@dawn-ai/sdk"
   import type { RouteTools } from "dawn:routes"
   import type { z } from "zod"
   import type state from "./state.js"

   type <RouteName>State = z.infer<typeof state> & { readonly tenant: string }

   export async function workflow(
     state: <RouteName>State,
     ctx: RuntimeContext<RouteTools<"/<route-path>">>
   ) {
     // use ctx.tools.<toolName>() — fully typed
     return { ...state, /* updates */ }
   }
   \`\`\`

   **Graph** (LangGraph graph/workflow):
   \`\`\`ts
   export const graph = /* langgraph graph instance */
   \`\`\`

   **Chain** (LangChain LCEL Runnable):
   \`\`\`ts
   export const chain = /* LCEL runnable */
   \`\`\`

   **Agent** (default descriptor):
   \`\`\`ts
   import { agent } from "@dawn-ai/sdk"

   export default agent({
     model: "gpt-4o-mini",
     systemPrompt: "You are a helpful assistant.",
   })
   \`\`\`

4. Optionally create a \`tools/\` directory with co-located tools (see the "Add a tool" prompt).

5. Run \`dawn routes\` to confirm Dawn discovered the new route and what pathname it computed. Then \`dawn run '<pathname>'\` with the required state via stdin.

Constraints:
- Exactly one of default \`agent(...)\`, named \`workflow\`, named \`graph\`, or named \`chain\` may be exported from \`index.ts\`.
- Route groups in parentheses \`(public)\` are NOT part of the pathname.
- Dynamic segment values, such as \`tenant\`, come from the JSON input when invoking the parameterized route id.
- The \`RouteTools<"/path">\` type is auto-generated from tools in the route's \`tools/\` directory.

Reference: https://dawnai.org/llms.txt
`;

const WRITE_A_TEST = `Help me write a scenario test for a Dawn route. Dawn tests run with \`dawn test\`, are co-located with the route, and take the form of \`run.test.ts\` files that default-export scenario records.

1. In the route directory, create \`run.test.ts\`:

   \`\`\`ts
   export default [
     {
       name: "greets a single tenant",
       input: { tenant: "acme" },
       expect: {
         status: "passed",
         output: { tenant: "acme", greeting: "Hello, acme!" },
       },
     },
     {
       name: "handles a different tenant",
       input: { tenant: "globex" },
       expect: {
         status: "passed",
         output: { tenant: "globex", greeting: "Hello, globex!" },
       },
     },
   ]
   \`\`\`

2. \`input\` is the route's state — it must match the route's \`state.ts\` type.

3. \`expect.output\` is what the route should return after the route runs.

4. Run the scenarios:
   \`\`\`
   dawn test
   \`\`\`

5. Dawn runs each test against the in-process route runtime by default. To run a scenario against a live \`dawn dev\` server, set \`run: { url: "http://127.0.0.1:3001" }\` on that scenario. There is no command-level \`--url\` flag on \`dawn test\`.

6. For custom checks, use \`assert(result)\` with helpers from \`@dawn-ai/sdk/testing\`:
   \`\`\`ts
   import { expectOutput } from "@dawn-ai/sdk/testing"

   export default [
     {
       name: "custom assertion",
       input: { tenant: "acme" },
       expect: { status: "passed" },
       assert: (result) => {
         expectOutput(result, { greeting: "Hello, acme!" })
       },
     },
   ]
   \`\`\`

Constraints:
- \`run.test.ts\` must live in the route's directory, not a sibling.
- The file default-exports an array. There is no \`describe()\` or \`test()\` wrapper.
- \`expect.output\` is compared deep-equal to the route's output by default.
- Per-scenario tool mocking is not supported today; stub external dependencies inside the tool implementation or behind an environment flag.

Reference: https://dawnai.org/llms.txt
`;

const DEPLOY = `Help me deploy a Dawn app. Dawn itself is not a production runtime — it owns local development and the build step that produces LangGraph artifacts. Production runs on LangSmith or another runtime that consumes the generated entry files.

1. Verify the app before deployment:
   \`\`\`
   dawn verify
   dawn test
   \`\`\`
   Both must pass. \`dawn verify\` covers the app contract, route discovery, typegen, and dependency/env advisories; \`dawn test\` runs scenario tests against the in-process runtime.

2. Optionally catch protocol-shape issues by running selected scenarios against a live dev server. Add \`run: { url: "http://127.0.0.1:3001" }\` to those scenarios, then run:
   \`\`\`
   dawn dev --port 3001 &
   dawn test
   \`\`\`
   This exercises the LangSmith-style \`/runs/wait\` envelope locally. It is useful before deploy, but production still uses the \`dawn build\` artifacts.

3. Generate deployment artifacts:
   \`\`\`
   dawn build --clean
   \`\`\`
   This writes \`.dawn/build/langgraph.json\` and per-route entry files under \`.dawn/build/<routeSlug>.ts\`. Each generated assistant id is \`<routeId>#<kind>\`, for example \`/hello/[tenant]#agent\`.

4. Configure deployment:
   - Push to a Git remote connected to LangSmith.
   - LangSmith consumes the generated \`langgraph.json\` and route entry files.
   - LangSmith provisions assistants keyed by the generated \`assistant_id\` strings.

5. Show me a minimal generated \`.dawn/build/langgraph.json\` example:
   \`\`\`json
   {
     "graphs": {
       "/hello/[tenant]#agent": "./.dawn/build/hello-tenant.ts:graph"
     },
     "dependencies": ["."],
     "env": ".env.example",
     "node_version": "22"
   }
   \`\`\`

6. For infrastructure outside LangSmith, explain how to run the generated LangGraph entry files and \`langgraph.json\` in the target runtime. Treat \`dawn dev\` as a local reference surface, not a production server.

Reference: https://dawnai.org/llms.txt
`;

export const PROMPTS: readonly PromptEntry[] = [
	{
		slug: "scaffold",
		title: "Scaffold a new Dawn app",
		description: "Create a new Dawn project and walk through the structure.",
		body: SCAFFOLD,
	},
	{
		slug: "add-a-tool",
		title: "Add a tool",
		description: "Add a type-inferred tool to an existing route.",
		body: ADD_A_TOOL,
	},
	{
		slug: "write-a-route",
		title: "Write a route",
		description: "Create a new route with workflow/graph/chain.",
		body: WRITE_A_ROUTE,
	},
	{
		slug: "write-a-test",
		title: "Write a scenario test",
		description: "Write a colocated run.test.ts for a route.",
		body: WRITE_A_TEST,
	},
	{
		slug: "deploy",
		title: "Deploy",
		description: "Ship a Dawn app to LangSmith.",
		body: DEPLOY,
	},
];

export function getPrompt(slug: PromptSlug): PromptEntry {
	const entry = PROMPTS.find((p) => p.slug === slug);
	if (!entry) {
		throw new Error(`Unknown prompt slug: ${slug}`);
	}
	return entry;
}
