#!/bin/sh
# Shared image build for the full-arc sandbox smoke.
#
#   sh build-image.sh <k8s|docker> <verdaccio-registry-url>
#
# Builds the smoke Dawn app image the *user-facing* way: `dawn build` (node
# target) emits `.dawn/build/server.mjs` + a hardened `Dockerfile`, and we
# `docker build` that emitted Dockerfile. The only smoke-specific twist is that
# `@dawn-ai/*` is resolved from a local Verdaccio registry (published from this
# checkout) instead of npmjs — via a temporary `.npmrc` COPY'd into the image.
#
# Tags: `dawn-smoke-app:<k8s|docker>`. The `docker` variant additionally installs
# the `docker` CLI client (dockerSandbox shells out to `docker`).
#
# Networking follows Task 1's spike findings: the emitted Dockerfile's
# `npm ci`/`npm install` reaches the host Verdaccio via
# `host.docker.internal` + `--add-host=host.docker.internal:host-gateway`.
set -eu

VARIANT="${1:?usage: build-image.sh <k8s|docker> <verdaccio-registry-url>}"
REGISTRY_URL="${2:?usage: build-image.sh <k8s|docker> <verdaccio-registry-url>}"

case "$VARIANT" in
  k8s|docker) ;;
  *) echo "build-image.sh: variant must be 'k8s' or 'docker', got '$VARIANT'" >&2; exit 2 ;;
esac

# Resolve paths relative to this script so it works from any CWD.
SMOKE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
APP_DIR="$SMOKE_DIR/app"
TAG="dawn-smoke-app:$VARIANT"

# --- Registry URL forms -------------------------------------------------------
# Host form (for the on-host `npm install` that lets `dawn build` resolve the CLI).
HOST_REGISTRY="$REGISTRY_URL"
# Docker-build form: rewrite loopback host → host.docker.internal (Task 1).
DOCKER_REGISTRY=$(printf '%s' "$REGISTRY_URL" \
  | sed -e 's#//127\.0\.0\.1:#//host.docker.internal:#' \
        -e 's#//localhost:#//host.docker.internal:#')
# host:port token for the _authToken .npmrc key (Verdaccio wants a token even
# for its $anonymous/$all access).
DOCKER_HOSTPORT=$(printf '%s' "$DOCKER_REGISTRY" | sed -e 's#^https\{0,1\}://##' -e 's#/.*$##')

echo "==> build-image.sh: variant=$VARIANT"
echo "    host registry:   $HOST_REGISTRY"
echo "    docker registry: $DOCKER_REGISTRY"

# --- Step 1: dawn build (node target) ----------------------------------------
# Install the app's deps from Verdaccio so the `dawn` CLI + @dawn-ai/* resolve
# on the host, then run the node-target build. node_modules + lockfile are
# throwaway (removed before the docker build so they don't leak into the image).
echo "==> installing app deps from Verdaccio (host-side, for dawn build)"
# Use pnpm (the same client the Verdaccio harness publishes/installs with).
# NOT npm here: @dawn-ai/* republish the same version (0.8.x) across Verdaccio
# sessions with non-reproducible tarball bytes, so a developer's shared ~/.npm
# cache carries a stale integrity for that version and npm fails with EINTEGRITY.
# pnpm's content-addressed store verifies against the live packument and is
# immune. `--ignore-workspace` keeps this standalone app from being absorbed
# into the repo's pnpm workspace. The in-image `npm install` is unaffected — it
# runs in a pristine container with no prior cache.
( cd "$APP_DIR" && pnpm install --ignore-workspace --registry "$HOST_REGISTRY" )

echo "==> dawn build (node target)"
( cd "$APP_DIR" && ./node_modules/.bin/dawn build )

SERVER_MJS="$APP_DIR/.dawn/build/server.mjs"
EMITTED_DOCKERFILE="$APP_DIR/Dockerfile"
[ -f "$SERVER_MJS" ] || { echo "FATAL: $SERVER_MJS not emitted" >&2; exit 1; }
[ -f "$EMITTED_DOCKERFILE" ] || { echo "FATAL: $EMITTED_DOCKERFILE not emitted" >&2; exit 1; }
grep -q "Generated by dawn build (node target)" "$EMITTED_DOCKERFILE" \
  || { echo "FATAL: $EMITTED_DOCKERFILE lacks the node-target marker" >&2; exit 1; }
echo "    emitted: .dawn/build/server.mjs + marked Dockerfile OK"

# --- Step 2: make @dawn-ai/* resolve from Verdaccio inside the image ----------
# Smoke-only augmentation: a temporary .npmrc scoping @dawn-ai/* to Verdaccio,
# plus a single `COPY .npmrc ./` injected immediately BEFORE the `RUN npm ci`
# line of the emitted Dockerfile (which runs before `COPY . .`). Real users
# install @dawn-ai/* from npmjs and need none of this.
NPMRC="$APP_DIR/.npmrc"
cat > "$NPMRC" <<EOF
@dawn-ai:registry=$DOCKER_REGISTRY
//$DOCKER_HOSTPORT/:_authToken=smoke
# Serialize tarball fetches — the ephemeral Verdaccio streams tarballs on the fly
# and can occasionally serve a corrupt body under npm's default parallelism.
maxsockets=1
EOF

# Clean up injected files + host build artifacts on any exit so the tree stays
# clean (the emitted .dawn/ and Dockerfile are gitignored, but node_modules and
# .npmrc must not linger).
cleanup() {
  rm -f "$NPMRC"
  rm -rf "$APP_DIR/node_modules" "$APP_DIR/package-lock.json" "$APP_DIR/pnpm-lock.yaml"
  [ -f "$EMITTED_DOCKERFILE.smoke" ] && rm -f "$EMITTED_DOCKERFILE.smoke" || true
}
trap cleanup EXIT INT TERM

# Inject `COPY .npmrc ./` right before the `RUN npm ci ...` line. Write the
# augmented Dockerfile to a sibling file so the emitted one is left untouched.
# Also DROP the `# syntax=docker/dockerfile:1` directive: it forces BuildKit to
# pull the external dockerfile frontend image from docker.io, which is a hard
# network dependency the smoke doesn't need (the embedded frontend handles every
# instruction the node target emits). Stripping it keeps the build resilient in
# restricted/offline environments; on a normal runner it's a harmless no-op.
AUG_DOCKERFILE="$EMITTED_DOCKERFILE.smoke"
awk '
  /^# *syntax=/ { next }
  /^RUN npm ci/ && !done { print "COPY .npmrc ./"; done=1 }
  { print }
' "$EMITTED_DOCKERFILE" > "$AUG_DOCKERFILE"
grep -q "^COPY .npmrc ./" "$AUG_DOCKERFILE" \
  || { echo "FATAL: failed to inject 'COPY .npmrc ./' into the Dockerfile" >&2; exit 1; }

# Remove throwaway host node_modules/lockfiles BEFORE docker build so `COPY . .`
# doesn't drag them into the image (the image does its own `npm install`).
rm -rf "$APP_DIR/node_modules" "$APP_DIR/package-lock.json" "$APP_DIR/pnpm-lock.yaml"

# --- Step 3: docker build (Task 1 networking) --------------------------------
echo "==> docker build $TAG (via emitted node-target Dockerfile)"
docker build \
  --add-host=host.docker.internal:host-gateway \
  -f "$AUG_DOCKERFILE" \
  -t "$TAG" \
  "$APP_DIR"

# --- Step 4: docker variant — add the docker CLI client ----------------------
# dockerSandbox shells out to `docker`, so the docker variant needs the client
# binary in the image. Layer it on as root, then drop back to the non-root user.
if [ "$VARIANT" = "docker" ]; then
  echo "==> adding docker CLI client to $TAG"
  CLI_DOCKERFILE=$(mktemp)
  cat > "$CLI_DOCKERFILE" <<EOF
FROM $TAG
USER root
RUN apt-get update \\
 && apt-get install -y --no-install-recommends docker.io \\
 && rm -rf /var/lib/apt/lists/*
USER 1000:1000
EOF
  docker build -f "$CLI_DOCKERFILE" -t "$TAG" "$APP_DIR"
  rm -f "$CLI_DOCKERFILE"
fi

echo "==> built $TAG"
